server:
  http2:
    enabled: true

graphql:
  servlet:
    max-query-depth: 20
    exception-handlers-enabled: true
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account - query
        query: classpath:playground/bank_account_query.graphql
        variables: classpath:playground/bank_account_variables.json
      - name: Bank account - create
        query: classpath:playground/bank_account_create.graphql
        variables: classpath:playground/bank_account_variables.json
